-- Calendar-year 2026 MSP operational seed (mid-sized Nexus demo)
-- Idempotent fixed UUIDs. Regenerated by scripts/generate-2026-msp-seed.js

-- ---------------------------------------------------------------------------
-- New technicians: Kai Cipher + Quinn Volt (Auth + profiles + technician rows)
-- ---------------------------------------------------------------------------


insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '22222222-2222-2222-2222-222222222211',
  'authenticated',
  'authenticated',
  'kai@nexus.demo',
  extensions.crypt('DemoPass123!', extensions.gen_salt('bf')),
  now(),
  jsonb_build_object('provider','email','providers',jsonb_build_array('email')),
  jsonb_build_object('full_name','Kai Cipher','role','technician'),
  now(), now(), '', '', '', ''
)
on conflict (id) do update
  set email = excluded.email,
      email_confirmed_at = coalesce(auth.users.email_confirmed_at, excluded.email_confirmed_at),
      encrypted_password = excluded.encrypted_password,
      raw_user_meta_data = excluded.raw_user_meta_data,
      updated_at = now();

insert into auth.identities (
  id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
) values (
  '22222222-2222-2222-2222-222222222211',
  '22222222-2222-2222-2222-222222222211',
  jsonb_build_object('sub','22222222-2222-2222-2222-222222222211','email','kai@nexus.demo'),
  'email',
  '22222222-2222-2222-2222-222222222211',
  now(), now(), now()
)
on conflict (provider_id, provider) do update
  set user_id = excluded.user_id,
      identity_data = excluded.identity_data,
      updated_at = now();

insert into public.profiles (id, full_name, email, role, active)
values ('22222222-2222-2222-2222-222222222211', 'Kai Cipher', 'kai@nexus.demo', 'technician', true)
on conflict (id) do update
  set full_name = excluded.full_name,
      email = excluded.email,
      role = 'technician',
      active = true;

insert into public.technicians (
  id, profile_id, technician_name, specialty, internal_hourly_cost, hourly_rate, annual_pto_hours, active
) values (
  '33333333-3333-3333-3333-333333333308', '22222222-2222-2222-2222-222222222211', 'Kai Cipher', 'Security Operations', 64, 130, 80, true
)
on conflict (id) do update
  set profile_id = excluded.profile_id,
      technician_name = excluded.technician_name,
      specialty = excluded.specialty,
      internal_hourly_cost = excluded.internal_hourly_cost,
      hourly_rate = excluded.hourly_rate,
      active = true;

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '22222222-2222-2222-2222-222222222212',
  'authenticated',
  'authenticated',
  'quinn@nexus.demo',
  extensions.crypt('DemoPass123!', extensions.gen_salt('bf')),
  now(),
  jsonb_build_object('provider','email','providers',jsonb_build_array('email')),
  jsonb_build_object('full_name','Quinn Volt','role','technician'),
  now(), now(), '', '', '', ''
)
on conflict (id) do update
  set email = excluded.email,
      email_confirmed_at = coalesce(auth.users.email_confirmed_at, excluded.email_confirmed_at),
      encrypted_password = excluded.encrypted_password,
      raw_user_meta_data = excluded.raw_user_meta_data,
      updated_at = now();

insert into auth.identities (
  id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
) values (
  '22222222-2222-2222-2222-222222222212',
  '22222222-2222-2222-2222-222222222212',
  jsonb_build_object('sub','22222222-2222-2222-2222-222222222212','email','quinn@nexus.demo'),
  'email',
  '22222222-2222-2222-2222-222222222212',
  now(), now(), now()
)
on conflict (provider_id, provider) do update
  set user_id = excluded.user_id,
      identity_data = excluded.identity_data,
      updated_at = now();

insert into public.profiles (id, full_name, email, role, active)
values ('22222222-2222-2222-2222-222222222212', 'Quinn Volt', 'quinn@nexus.demo', 'technician', true)
on conflict (id) do update
  set full_name = excluded.full_name,
      email = excluded.email,
      role = 'technician',
      active = true;

insert into public.technicians (
  id, profile_id, technician_name, specialty, internal_hourly_cost, hourly_rate, annual_pto_hours, active
) values (
  '33333333-3333-3333-3333-333333333309', '22222222-2222-2222-2222-222222222212', 'Quinn Volt', 'Infrastructure & Power Systems', 56, 112, 80, true
)
on conflict (id) do update
  set profile_id = excluded.profile_id,
      technician_name = excluded.technician_name,
      specialty = excluded.specialty,
      internal_hourly_cost = excluded.internal_hourly_cost,
      hourly_rate = excluded.hourly_rate,
      active = true;

insert into public.technician_expense_budgets (technician_id, monthly_limit)
select id, 250 from public.technicians
where id in ('33333333-3333-3333-3333-333333333308','33333333-3333-3333-3333-333333333309')
on conflict (technician_id) do nothing;

insert into public.technician_parts_budgets (technician_id, monthly_limit)
select id, 500 from public.technicians
where id in ('33333333-3333-3333-3333-333333333308','33333333-3333-3333-3333-333333333309')
on conflict (technician_id) do nothing;

-- ---------------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------------

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111101', 'Northwind Manufacturing', 'Manufacturing', 'Casey Plant', 'clientuser@nexus.demo',
  '(662) 555-0101', '1200 Industrial Parkway', 'Oxford', 'MS', '38655',
  'Active', 'Managed IT client under Nexus Gold plan.',
  '33333333-3333-3333-3333-333333333303', 86
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111102', 'Beacon Legal Group', 'Legal', 'Pat Rivera', 'clientadmin@nexus.demo',
  '(662) 555-0102', '44 Courthouse Square', 'Oxford', 'MS', '38655',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 82
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111103', 'Harbor Retail Collective', 'Retail', 'Sam Harbor', 'ops@harborretail.demo',
  '(601) 555-0103', '890 Market Street', 'Jackson', 'MS', '39201',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 78
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111104', 'Summit Family Clinics', 'Healthcare', 'Dr. Riley Summit', 'it@summitclinics.demo',
  '(601) 555-0104', '215 Wellness Drive', 'Ridgeland', 'MS', '39157',
  'Active', 'Managed IT client under Nexus Gold plan.',
  '33333333-3333-3333-3333-333333333303', 88
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111105', 'Cedar County Schools', 'Education', 'Jordan Cedar', 'tech@cedarschools.demo',
  '(662) 555-0105', '1 Eagle Drive', 'Pontotoc', 'MS', '38863',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 74
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111106', 'PixelCraft Studio', 'Media & Design', 'Alex Pixel', 'hello@pixelcraft.demo',
  '(662) 555-0106', '18 Gallery Lane', 'Oxford', 'MS', '38655',
  'Active', 'Managed IT client under Nexus Essentials plan.',
  '33333333-3333-3333-3333-333333333303', 80
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111107', 'Lakeside Logistics', 'Transportation', 'Morgan Lake', 'dispatch@lakesidelogistics.demo',
  '(662) 555-0107', '500 Freight Way', 'Southaven', 'MS', '38671',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 76
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111108', 'Greenfield Credit Union', 'Financial Services', 'Taylor Green', 'security@greenfieldcu.demo',
  '(601) 555-0108', '77 Main Street', 'Hattiesburg', 'MS', '39401',
  'Active', 'Managed IT client under Nexus Gold plan.',
  '33333333-3333-3333-3333-333333333303', 91
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

-- Link portal demos to their organizations
update public.profiles
set customer_id = '11111111-1111-1111-1111-111111111101',
    role = 'client_user',
    full_name = coalesce(nullif(full_name,''), 'Casey Plant'),
    active = true
where id = '33333333-3333-3333-3333-333333333307';

update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
  || jsonb_build_object('role','client_user','customer_id','11111111-1111-1111-1111-111111111101','full_name','Casey Plant')
where id = '33333333-3333-3333-3333-333333333307';

update public.profiles
set customer_id = '11111111-1111-1111-1111-111111111102',
    role = 'client_user',
    active = true
where id = '33333333-3333-3333-3333-333333333306';

update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
  || jsonb_build_object('role','client_user','customer_id','11111111-1111-1111-1111-111111111102')
where id = '33333333-3333-3333-3333-333333333306';

-- ---------------------------------------------------------------------------
-- Contracts (Active through 2026)
-- ---------------------------------------------------------------------------

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000001', '11111111-1111-1111-1111-111111111101', 'Northwind Manufacturing — Gold 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Gold', 4500, 40, 145, 217.5, 166.75,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555503', 40000, 1, 1.5, 30,
  '2026 managed services agreement for Northwind Manufacturing.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000002', '11111111-1111-1111-1111-111111111102', 'Beacon Legal Group — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Beacon Legal Group.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000003', '11111111-1111-1111-1111-111111111103', 'Harbor Retail Collective — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Harbor Retail Collective.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000004', '11111111-1111-1111-1111-111111111104', 'Summit Family Clinics — Gold 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Gold', 4500, 40, 145, 217.5, 166.75,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555503', 40000, 1, 1.5, 30,
  '2026 managed services agreement for Summit Family Clinics.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000005', '11111111-1111-1111-1111-111111111105', 'Cedar County Schools — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Cedar County Schools.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000006', '11111111-1111-1111-1111-111111111106', 'PixelCraft Studio — Essentials 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Essentials', 1800, 10, 160, 240, 184,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555501', 5000, 1, 1.5, 30,
  '2026 managed services agreement for PixelCraft Studio.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000007', '11111111-1111-1111-1111-111111111107', 'Lakeside Logistics — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Lakeside Logistics.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000008', '11111111-1111-1111-1111-111111111108', 'Greenfield Credit Union — Gold 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Gold', 4500, 40, 145, 217.5, 166.75,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555503', 40000, 1, 1.5, 30,
  '2026 managed services agreement for Greenfield Credit Union.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

-- Clear prior 2026 seed operational rows (safe fixed UUID prefixes)
delete from public.payments where id::text like 'a6267400%';

delete from public.ticket_expenses where id::text like 'a6267600%';

delete from public.work_entries where id::text like 'a6267200%';

delete from public.invoices where id::text like 'a6267300%';

delete from public.service_tickets where id::text like 'a6267100%';

delete from public.hardware_assets where id::text like 'a6267500%';

delete from public.security_scores where id::text like 'a6267800%';

