-- Calendar-year 2026 MSP operational seed (mid-sized Nexus demo)
-- Idempotent fixed UUIDs. Regenerated by scripts/generate-2026-msp-seed.js

-- ---------------------------------------------------------------------------
-- New technicians: Kai Cipher + Quinn Volt (Auth + profiles + technician rows)
-- ---------------------------------------------------------------------------


insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '22222222-2222-2222-2222-222222222211',
  'authenticated',
  'authenticated',
  'kai@nexus.demo',
  extensions.crypt('DemoPass123!', extensions.gen_salt('bf')),
  now(),
  jsonb_build_object('provider','email','providers',jsonb_build_array('email')),
  jsonb_build_object('full_name','Kai Cipher','role','technician'),
  now(), now(), '', '', '', ''
)
on conflict (id) do update
  set email = excluded.email,
      email_confirmed_at = coalesce(auth.users.email_confirmed_at, excluded.email_confirmed_at),
      encrypted_password = excluded.encrypted_password,
      raw_user_meta_data = excluded.raw_user_meta_data,
      updated_at = now();

insert into auth.identities (
  id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
) values (
  '22222222-2222-2222-2222-222222222211',
  '22222222-2222-2222-2222-222222222211',
  jsonb_build_object('sub','22222222-2222-2222-2222-222222222211','email','kai@nexus.demo'),
  'email',
  '22222222-2222-2222-2222-222222222211',
  now(), now(), now()
)
on conflict (provider_id, provider) do update
  set user_id = excluded.user_id,
      identity_data = excluded.identity_data,
      updated_at = now();

insert into public.profiles (id, full_name, email, role, active)
values ('22222222-2222-2222-2222-222222222211', 'Kai Cipher', 'kai@nexus.demo', 'technician', true)
on conflict (id) do update
  set full_name = excluded.full_name,
      email = excluded.email,
      role = 'technician',
      active = true;

insert into public.technicians (
  id, profile_id, technician_name, specialty, internal_hourly_cost, hourly_rate, annual_pto_hours, active
) values (
  '33333333-3333-3333-3333-333333333308', '22222222-2222-2222-2222-222222222211', 'Kai Cipher', 'Security Operations', 64, 130, 80, true
)
on conflict (id) do update
  set profile_id = excluded.profile_id,
      technician_name = excluded.technician_name,
      specialty = excluded.specialty,
      internal_hourly_cost = excluded.internal_hourly_cost,
      hourly_rate = excluded.hourly_rate,
      active = true;

insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change
) values (
  '00000000-0000-0000-0000-000000000000',
  '22222222-2222-2222-2222-222222222212',
  'authenticated',
  'authenticated',
  'quinn@nexus.demo',
  extensions.crypt('DemoPass123!', extensions.gen_salt('bf')),
  now(),
  jsonb_build_object('provider','email','providers',jsonb_build_array('email')),
  jsonb_build_object('full_name','Quinn Volt','role','technician'),
  now(), now(), '', '', '', ''
)
on conflict (id) do update
  set email = excluded.email,
      email_confirmed_at = coalesce(auth.users.email_confirmed_at, excluded.email_confirmed_at),
      encrypted_password = excluded.encrypted_password,
      raw_user_meta_data = excluded.raw_user_meta_data,
      updated_at = now();

insert into auth.identities (
  id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
) values (
  '22222222-2222-2222-2222-222222222212',
  '22222222-2222-2222-2222-222222222212',
  jsonb_build_object('sub','22222222-2222-2222-2222-222222222212','email','quinn@nexus.demo'),
  'email',
  '22222222-2222-2222-2222-222222222212',
  now(), now(), now()
)
on conflict (provider_id, provider) do update
  set user_id = excluded.user_id,
      identity_data = excluded.identity_data,
      updated_at = now();

insert into public.profiles (id, full_name, email, role, active)
values ('22222222-2222-2222-2222-222222222212', 'Quinn Volt', 'quinn@nexus.demo', 'technician', true)
on conflict (id) do update
  set full_name = excluded.full_name,
      email = excluded.email,
      role = 'technician',
      active = true;

insert into public.technicians (
  id, profile_id, technician_name, specialty, internal_hourly_cost, hourly_rate, annual_pto_hours, active
) values (
  '33333333-3333-3333-3333-333333333309', '22222222-2222-2222-2222-222222222212', 'Quinn Volt', 'Infrastructure & Power Systems', 56, 112, 80, true
)
on conflict (id) do update
  set profile_id = excluded.profile_id,
      technician_name = excluded.technician_name,
      specialty = excluded.specialty,
      internal_hourly_cost = excluded.internal_hourly_cost,
      hourly_rate = excluded.hourly_rate,
      active = true;

insert into public.technician_expense_budgets (technician_id, monthly_limit)
select id, 250 from public.technicians
where id in ('33333333-3333-3333-3333-333333333308','33333333-3333-3333-3333-333333333309')
on conflict (technician_id) do nothing;

insert into public.technician_parts_budgets (technician_id, monthly_limit)
select id, 500 from public.technicians
where id in ('33333333-3333-3333-3333-333333333308','33333333-3333-3333-3333-333333333309')
on conflict (technician_id) do nothing;

-- ---------------------------------------------------------------------------
-- Customers
-- ---------------------------------------------------------------------------

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111101', 'Northwind Manufacturing', 'Manufacturing', 'Casey Plant', 'clientuser@nexus.demo',
  '(662) 555-0101', '1200 Industrial Parkway', 'Oxford', 'MS', '38655',
  'Active', 'Managed IT client under Nexus Gold plan.',
  '33333333-3333-3333-3333-333333333303', 86
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111102', 'Beacon Legal Group', 'Legal', 'Pat Rivera', 'clientadmin@nexus.demo',
  '(662) 555-0102', '44 Courthouse Square', 'Oxford', 'MS', '38655',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 82
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111103', 'Harbor Retail Collective', 'Retail', 'Sam Harbor', 'ops@harborretail.demo',
  '(601) 555-0103', '890 Market Street', 'Jackson', 'MS', '39201',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 78
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111104', 'Summit Family Clinics', 'Healthcare', 'Dr. Riley Summit', 'it@summitclinics.demo',
  '(601) 555-0104', '215 Wellness Drive', 'Ridgeland', 'MS', '39157',
  'Active', 'Managed IT client under Nexus Gold plan.',
  '33333333-3333-3333-3333-333333333303', 88
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111105', 'Cedar County Schools', 'Education', 'Jordan Cedar', 'tech@cedarschools.demo',
  '(662) 555-0105', '1 Eagle Drive', 'Pontotoc', 'MS', '38863',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 74
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111106', 'PixelCraft Studio', 'Media & Design', 'Alex Pixel', 'hello@pixelcraft.demo',
  '(662) 555-0106', '18 Gallery Lane', 'Oxford', 'MS', '38655',
  'Active', 'Managed IT client under Nexus Essentials plan.',
  '33333333-3333-3333-3333-333333333303', 80
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111107', 'Lakeside Logistics', 'Transportation', 'Morgan Lake', 'dispatch@lakesidelogistics.demo',
  '(662) 555-0107', '500 Freight Way', 'Southaven', 'MS', '38671',
  'Active', 'Managed IT client under Nexus Silver plan.',
  '33333333-3333-3333-3333-333333333303', 76
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

insert into public.customers (
  id, customer_name, industry, primary_contact_name, contact_email, contact_phone,
  address, city, state, zip_code, status, notes, account_manager_id, technology_health_score
) values (
  '11111111-1111-1111-1111-111111111108', 'Greenfield Credit Union', 'Financial Services', 'Taylor Green', 'security@greenfieldcu.demo',
  '(601) 555-0108', '77 Main Street', 'Hattiesburg', 'MS', '39401',
  'Active', 'Managed IT client under Nexus Gold plan.',
  '33333333-3333-3333-3333-333333333303', 91
)
on conflict (id) do update set
  customer_name = excluded.customer_name,
  industry = excluded.industry,
  primary_contact_name = excluded.primary_contact_name,
  contact_email = excluded.contact_email,
  contact_phone = excluded.contact_phone,
  address = excluded.address,
  city = excluded.city,
  state = excluded.state,
  zip_code = excluded.zip_code,
  status = 'Active',
  account_manager_id = excluded.account_manager_id,
  technology_health_score = excluded.technology_health_score;

-- Link portal demos to their organizations
update public.profiles
set customer_id = '11111111-1111-1111-1111-111111111101',
    role = 'client_user',
    full_name = coalesce(nullif(full_name,''), 'Casey Plant'),
    active = true
where id = '33333333-3333-3333-3333-333333333307';

update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
  || jsonb_build_object('role','client_user','customer_id','11111111-1111-1111-1111-111111111101','full_name','Casey Plant')
where id = '33333333-3333-3333-3333-333333333307';

update public.profiles
set customer_id = '11111111-1111-1111-1111-111111111102',
    role = 'client_user',
    active = true
where id = '33333333-3333-3333-3333-333333333306';

update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb)
  || jsonb_build_object('role','client_user','customer_id','11111111-1111-1111-1111-111111111102')
where id = '33333333-3333-3333-3333-333333333306';

-- ---------------------------------------------------------------------------
-- Contracts (Active through 2026)
-- ---------------------------------------------------------------------------

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000001', '11111111-1111-1111-1111-111111111101', 'Northwind Manufacturing — Gold 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Gold', 4500, 40, 145, 217.5, 166.75,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555503', 40000, 1, 1.5, 30,
  '2026 managed services agreement for Northwind Manufacturing.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000002', '11111111-1111-1111-1111-111111111102', 'Beacon Legal Group — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Beacon Legal Group.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000003', '11111111-1111-1111-1111-111111111103', 'Harbor Retail Collective — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Harbor Retail Collective.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000004', '11111111-1111-1111-1111-111111111104', 'Summit Family Clinics — Gold 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Gold', 4500, 40, 145, 217.5, 166.75,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555503', 40000, 1, 1.5, 30,
  '2026 managed services agreement for Summit Family Clinics.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000005', '11111111-1111-1111-1111-111111111105', 'Cedar County Schools — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Cedar County Schools.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000006', '11111111-1111-1111-1111-111111111106', 'PixelCraft Studio — Essentials 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Essentials', 1800, 10, 160, 240, 184,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555501', 5000, 1, 1.5, 30,
  '2026 managed services agreement for PixelCraft Studio.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000007', '11111111-1111-1111-1111-111111111107', 'Lakeside Logistics — Silver 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Silver', 2800, 20, 155, 232.5, 178.25,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555502', 15000, 1, 1.5, 30,
  '2026 managed services agreement for Lakeside Logistics.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

insert into public.contracts (
  id, customer_id, contract_name, contract_status, start_date, end_date, renewal_date,
  automatic_renewal, service_plan_name, monthly_recurring_fee, included_support_hours,
  additional_hourly_rate, emergency_support_rate, onsite_support_rate,
  remote_support_included, onsite_support_included, preventive_maintenance_frequency,
  critical_response_target_hours, high_response_target_hours, standard_response_target_hours,
  resolution_target_hours, support_coverage, billing_frequency, payment_terms, invoice_due_days,
  setup_fee, pass_through_charges_allowed, revenue_recognition_method, approval_status,
  plan_id, included_asset_budget, additional_asset_rate, late_fee_percent, late_fee_period_days,
  notes, included_services
) values (
  'a6267700-0000-4000-8000-000000000008', '11111111-1111-1111-1111-111111111108', 'Greenfield Credit Union — Gold 2026',
  'Active', '2026-01-01', '2026-12-31', '2026-12-01', true,
  'Gold', 4500, 40, 145, 217.5, 166.75,
  true, true, 'Quarterly', 1, 4, 8, 24,
  'Business hours Mon-Fri 8am-5pm CT', 'Monthly', 'Net 30', 30, 0, true,
  'Monthly over service period', 'Approved', '55555555-5555-5555-5555-555555555503', 40000, 1, 1.5, 30,
  '2026 managed services agreement for Greenfield Credit Union.',
  array['Remote support','Patch management','Backup monitoring','Help desk']
)
on conflict (id) do update set
  contract_status = 'Active',
  approval_status = 'Approved',
  monthly_recurring_fee = excluded.monthly_recurring_fee,
  included_support_hours = excluded.included_support_hours,
  plan_id = excluded.plan_id,
  end_date = excluded.end_date;

-- Clear prior 2026 seed operational rows (safe fixed UUID prefixes)
delete from public.payments where id::text like 'a6267400%';

delete from public.ticket_expenses where id::text like 'a6267600%';

delete from public.work_entries where id::text like 'a6267200%';

delete from public.invoices where id::text like 'a6267300%';

delete from public.service_tickets where id::text like 'a6267100%';

delete from public.hardware_assets where id::text like 'a6267500%';

delete from public.security_scores where id::text like 'a6267800%';

-- Service tickets (331)
insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000001', 'TKT-2026-0001', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Laptop imaging and join to Entra ID — Northwind',
  'Hardware Deployment request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Deployment', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333303', '2026-01-05T09:05:00-05:00', '2026-01-05T12:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-01-05T09:00:00-05:00', 'h09x3',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000002', 'TKT-2026-0002', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'M365 mailbox restore request — Northwind',
  'Microsoft 365 request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Microsoft 365', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333304', '2026-01-07T11:05:00-05:00', '2026-01-07T13:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-01-07T11:00:00-05:00', 'h11',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000003', 'TKT-2026-0003', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Patch cycle review and reboot window — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333305', '2026-01-12T13:05:00-05:00', '2026-01-12T15:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-01-12T13:00:00-05:00', 'h13',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000004', 'TKT-2026-0004', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Firewall rule change for vendor access — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333306', '2026-01-15T15:05:00-05:00', '2026-01-15T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-01-15T15:00:00-05:00', 'h15',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000005', 'TKT-2026-0005', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Endpoint AV quarantine investigation — Northwind',
  'Cybersecurity request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cybersecurity', 'Critical', 'Remote',
  '33333333-3333-3333-3333-333333333308', '2026-01-19T09:05:00-05:00', '2026-01-19T12:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-01-19T09:00:00-05:00', 'h09x3',
  4, 4, false, false, false, true,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000006', 'TKT-2026-0006', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Printer mapping and driver cleanup — Northwind',
  'Hardware Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Support', 'Low', 'On-site',
  '33333333-3333-3333-3333-333333333309', '2026-01-05T11:05:00-05:00', '2026-01-05T13:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-01-05T11:00:00-05:00', 'h11',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000007', 'TKT-2026-0007', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Shared drive permissions update — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333302', '2026-02-03T15:05:00-05:00', '2026-02-03T16:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-02-03T15:00:00-05:00', 'h15',
  2, 2, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000008', 'TKT-2026-0008', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Wi-Fi dead spot survey — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333303', '2026-02-09T09:05:00-05:00', '2026-02-09T13:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-02-09T09:00:00-05:00', 'h09x3',
  5, 5, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000009', 'TKT-2026-0009', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Backup job failure triage — Northwind',
  'Cloud request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cloud', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333304', '2026-02-11T11:05:00-05:00', '2026-02-11T14:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-02-11T11:00:00-05:00', 'h11',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000000a', 'TKT-2026-0010', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'New hire workstation setup — Northwind',
  'Hardware Deployment request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Deployment', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333305', '2026-02-16T13:05:00-05:00', '2026-02-16T15:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-02-16T13:00:00-05:00', 'h13',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000000b', 'TKT-2026-0011', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Phishing report triage — Northwind',
  'Cybersecurity request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cybersecurity', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333306', '2026-02-19T15:05:00-05:00', '2026-02-19T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-02-19T15:00:00-05:00', 'h15',
  3, 3, false, false, false, true,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000000c', 'TKT-2026-0012', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Server disk capacity expansion — Northwind',
  'Cloud request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cloud', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333308', '2026-02-03T09:05:00-05:00', '2026-02-03T12:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-02-03T09:00:00-05:00', 'h09x3',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000000d', 'TKT-2026-0013', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'QoS tuning for VoIP quality — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333301', '2026-03-03T13:05:00-05:00', '2026-03-03T15:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-03-03T13:00:00-05:00', 'h13',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000000e', 'TKT-2026-0014', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Application licensing renewal assist — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Low', 'Remote',
  '33333333-3333-3333-3333-333333333302', '2026-03-09T15:05:00-05:00', '2026-03-09T16:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-03-09T15:00:00-05:00', 'h15',
  2, 2, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000000f', 'TKT-2026-0015', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'VPN dropouts for remote staff — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333303', '2026-03-11T09:05:00-05:00', '2026-03-11T12:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-03-11T09:00:00-05:00', 'h09',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000010', 'TKT-2026-0016', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Laptop imaging and join to Entra ID — Northwind',
  'Hardware Deployment request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Deployment', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333304', '2026-03-16T11:05:00-05:00', '2026-03-16T14:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-03-16T11:00:00-05:00', 'h11x3',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000011', 'TKT-2026-0017', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'M365 mailbox restore request — Northwind',
  'Microsoft 365 request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Microsoft 365', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333305', '2026-03-19T13:05:00-05:00', '2026-03-19T15:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-03-19T13:00:00-05:00', 'h13',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000012', 'TKT-2026-0018', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Patch cycle review and reboot window — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333306', '2026-03-03T15:05:00-05:00', '2026-03-03T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-03-03T15:00:00-05:00', 'h15',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000013', 'TKT-2026-0019', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Firewall rule change for vendor access — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333309', '2026-04-03T11:05:00-05:00', '2026-04-03T13:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-04-03T11:00:00-05:00', 'h11',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000014', 'TKT-2026-0020', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Endpoint AV quarantine investigation — Northwind',
  'Cybersecurity request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cybersecurity', 'Critical', 'Remote',
  '33333333-3333-3333-3333-333333333301', '2026-04-07T13:05:00-05:00', '2026-04-07T16:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-04-07T13:00:00-05:00', 'h13x3',
  4, 4, false, false, false, true,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000015', 'TKT-2026-0021', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Printer mapping and driver cleanup — Northwind',
  'Hardware Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Support', 'Low', 'On-site',
  '33333333-3333-3333-3333-333333333302', '2026-04-13T15:05:00-05:00', '2026-04-13T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-04-13T15:00:00-05:00', 'h15',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000016', 'TKT-2026-0022', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Shared drive permissions update — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333303', '2026-04-15T09:05:00-05:00', '2026-04-15T10:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-04-15T09:00:00-05:00', 'h09',
  2, 2, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000017', 'TKT-2026-0023', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Wi-Fi dead spot survey — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333304', '2026-04-20T11:05:00-05:00', '2026-04-20T15:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-04-20T11:00:00-05:00', 'h11x3',
  5, 5, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000018', 'TKT-2026-0024', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Backup job failure triage — Northwind',
  'Cloud request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cloud', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333305', '2026-04-03T13:05:00-05:00', '2026-04-03T16:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-04-03T13:00:00-05:00', 'h13',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000019', 'TKT-2026-0025', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'New hire workstation setup — Northwind',
  'Hardware Deployment request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Deployment', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333308', '2026-05-04T09:05:00-05:00', '2026-05-04T11:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-05-04T09:00:00-05:00', 'h09',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000001a', 'TKT-2026-0026', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Phishing report triage — Northwind',
  'Cybersecurity request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cybersecurity', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333309', '2026-05-07T11:05:00-05:00', '2026-05-07T13:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-05-07T11:00:00-05:00', 'h11',
  3, 3, false, false, false, true,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000001b', 'TKT-2026-0027', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Server disk capacity expansion — Northwind',
  'Cloud request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cloud', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333301', '2026-05-11T13:05:00-05:00', '2026-05-11T16:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-05-11T13:00:00-05:00', 'h13x3',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000001c', 'TKT-2026-0028', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'QoS tuning for VoIP quality — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333302', '2026-05-15T15:05:00-05:00', '2026-05-15T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-05-15T15:00:00-05:00', 'h15',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000001d', 'TKT-2026-0029', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Application licensing renewal assist — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Low', 'Remote',
  '33333333-3333-3333-3333-333333333303', '2026-05-19T09:05:00-05:00', '2026-05-19T10:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-05-19T09:00:00-05:00', 'h09',
  2, 2, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000001e', 'TKT-2026-0030', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'VPN dropouts for remote staff — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333304', '2026-05-04T11:05:00-05:00', '2026-05-04T14:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-05-04T11:00:00-05:00', 'h11',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-00000000001f', 'TKT-2026-0031', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Laptop imaging and join to Entra ID — Northwind',
  'Hardware Deployment request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Deployment', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333306', '2026-06-03T15:05:00-05:00', '2026-06-03T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-06-03T15:00:00-05:00', 'h15x3',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000020', 'TKT-2026-0032', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'M365 mailbox restore request — Northwind',
  'Microsoft 365 request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Microsoft 365', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333308', '2026-06-08T09:05:00-05:00', '2026-06-08T11:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-06-08T09:00:00-05:00', 'h09',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000021', 'TKT-2026-0033', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Patch cycle review and reboot window — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333309', '2026-06-11T11:05:00-05:00', '2026-06-11T13:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-06-11T11:00:00-05:00', 'h11',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000022', 'TKT-2026-0034', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Firewall rule change for vendor access — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333301', '2026-06-15T13:05:00-05:00', '2026-06-15T15:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-06-15T13:00:00-05:00', 'h13',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000023', 'TKT-2026-0035', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Endpoint AV quarantine investigation — Northwind',
  'Cybersecurity request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cybersecurity', 'Critical', 'Remote',
  '33333333-3333-3333-3333-333333333302', '2026-06-19T15:05:00-05:00', '2026-06-19T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-06-19T15:00:00-05:00', 'h15x3',
  4, 4, false, false, false, true,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000024', 'TKT-2026-0036', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Printer mapping and driver cleanup — Northwind',
  'Hardware Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Hardware Support', 'Low', 'On-site',
  '33333333-3333-3333-3333-333333333303', '2026-06-03T09:05:00-05:00', '2026-06-03T11:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-06-03T09:00:00-05:00', 'h09',
  3, 3, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000025', 'TKT-2026-0037', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Shared drive permissions update — Northwind',
  'Software Support request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Software Support', 'Medium', 'Remote',
  '33333333-3333-3333-3333-333333333305', '2026-07-03T13:05:00-05:00', '2026-07-03T14:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-07-03T13:00:00-05:00', 'h13',
  2, 2, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000026', 'TKT-2026-0038', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Wi-Fi dead spot survey — Northwind',
  'Network request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Network', 'Medium', 'On-site',
  '33333333-3333-3333-3333-333333333306', '2026-07-07T15:05:00-05:00', '2026-07-07T17:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-07-07T15:00:00-05:00', 'h15x3',
  5, 5, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);

insert into public.service_tickets (
  id, ticket_number, customer_id, contract_id, title, description, category, priority, service_method,
  assigned_technician_id, opened_at, completed_at, status, requester_name, requester_email,
  resolution_notes, scheduled_start, scheduled_window, max_hours, allocated_hours,
  customer_approval_required, additional_work_suspected, ai_involved, cybersecurity_incident,
  additional_billable_work, is_asap, scheduled_off_requested_day, customer_rescheduled, en_route,
  live_timer_banked_seconds, live_timer_paused, notes
) values (
  'a6267100-0000-4000-8000-000000000027', 'TKT-2026-0039', '11111111-1111-1111-1111-111111111101', 'a6267700-0000-4000-8000-000000000001', 'Backup job failure triage — Northwind',
  'Cloud request logged for Northwind Manufacturing. Handled under Gold included hours where possible.', 'Cloud', 'High', 'Remote',
  '33333333-3333-3333-3333-333333333308', '2026-07-13T09:05:00-05:00', '2026-07-13T12:20:00-05:00',
  'Completed', 'Casey Plant', 'clientuser@nexus.demo',
  'Resolved for Casey Plant. Changes documented and validated with end users.', '2026-07-13T09:00:00-05:00', 'h09',
  4, 4, false, false, false, false,
  false, false, false, false, false, 0, false,
  'Seeded 2026 MSP operations history.'
);
